#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D sourceImage;
layout(rgba16f, set = 0, binding = 1) uniform image2D targetImage;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(targetImage);
    if (any(greaterThanEqual(pixel, size))) return;
    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
    vec2 texel = 1.0 / vec2(textureSize(sourceImage, 0));
    vec3 color = vec3(0.0);
    color += textureLod(sourceImage, uv + texel * vec2(-1, -1), 0.0).rgb * 0.0625;
    color += textureLod(sourceImage, uv + texel * vec2( 0, -1), 0.0).rgb * 0.125;
    color += textureLod(sourceImage, uv + texel * vec2( 1, -1), 0.0).rgb * 0.0625;
    color += textureLod(sourceImage, uv + texel * vec2(-1,  0), 0.0).rgb * 0.125;
    color += textureLod(sourceImage, uv, 0.0).rgb * 0.25;
    color += textureLod(sourceImage, uv + texel * vec2( 1,  0), 0.0).rgb * 0.125;
    color += textureLod(sourceImage, uv + texel * vec2(-1,  1), 0.0).rgb * 0.0625;
    color += textureLod(sourceImage, uv + texel * vec2( 0,  1), 0.0).rgb * 0.125;
    color += textureLod(sourceImage, uv + texel * vec2( 1,  1), 0.0).rgb * 0.0625;
    imageStore(targetImage, pixel, imageLoad(targetImage, pixel) + vec4(color, 0.0));
}
